That heartless man...abandoning me at six months pregnant?

I can't let that happen...

Ah, the widow's pension. That should be enough to raise my child...

But how shall I go about this? I'll need something heavy and not out of place.

Maybe I should start with the basement...